//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TextEvalution.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TextEvalution.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ом,ем,ой,ей,ьей,ых,их,ым,им,ьим,ой,ей,ьей,ыми,ими,ьими,ой,ого,ий,его,ую,ью,ое,ее,ье,ые,ых,ие,их,ьи,ому,ему,ьему,ой,ей,ьей,ым,им,ьим,ого,его,ьего,ой,ей,ьей,ых,их,ьих,ой,ий,ая,ья,ое,ее,ье,ые,ие,ьи.
        /// </summary>
        internal static string Adjectives_ending {
            get {
                return ResourceManager.GetString("Adjectives_ending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to а,я,о,е,ы,и.
        /// </summary>
        internal static string Adjectives_ending_short {
            get {
                return ResourceManager.GetString("Adjectives_ending_short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ешеньк,ошеньк,ехоньк,оханьк,тельн,янист,ическ,енск,инск,овит,оват,евит,ильн,еват,оньк,еньк,енн,онн,чат,лив,чив,ист,аст,ск,ат,ал,шн,ел,ан,ян,ив,ев,ем,им,ов,ен,ён,нн,ын,ин,жн,л.
        /// </summary>
        internal static string Adjectives_suffix {
            get {
                return ResourceManager.GetString("Adjectives_suffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ешеньк,ошеньк,ехоньк,оханьк,тельн,янист,ическ,енск,инск,овит,оват,евит,ильн,еват,оньк,еньк,енн,онн,чат,лив,чив,ист,аст,ск,ат,ал,шн,ел,ан,ян,ив,ев,ем,им,ов,ен,ён,нн,ын,ин.
        /// </summary>
        internal static string Adjectives_suffix_short {
            get {
                return ResourceManager.GetString("Adjectives_suffix_short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to абсолютно,автоматически,адекватно,азартно,аккурат,аккуратно,активно,бегло,бегом,бедно,безвозвратно,беззаботно,беззвучно,безмерно,безнадежно,безоговорочно,безошибочно,безразлично,безумно,безупречно,безуспешно,бережно,бесконечно,бесплатно,бесповоротно,беспокойно,бесполезно,беспомощно,беспощадно,беспрепятственно,беспрерывно,бессильно,бесследно,бессмысленно,бессознательно,бесшумно,бешено,биологически,битком,благополучно,блаженно,блестяще,близко,богато,бодро,более,болезненно,больно,больше,босиком,буквально,бурно [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Adverbs {
            get {
                return ResourceManager.GetString("Adverbs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to вшись,шись,ясь,учи,ючи.
        /// </summary>
        internal static string Deerpriests_ending {
            get {
                return ResourceManager.GetString("Deerpriests_ending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to а как же
        ///а то как же
        ///а то нет
        ///а толку что
        ///а толку-то
        ///а чего ж
        ///а что
        ///а что ж
        ///агу
        ///агуленьки
        ///агулечки
        ///агунюшки
        ///агушеньки
        ///адью
        ///ай
        ///ай да
        ///ай-люли
        ///ай-я-яй
        ///ай-яй-яй
        ///айда
        ///айда-те
        ///айдате
        ///аксиос
        ///алаверды
        ///алё
        ///алле
        ///алле-гоп
        ///аллилуйя
        ///алло
        ///ам
        ///ам-ам
        ///амба
        ///аминь
        ///анкор
        ///апорт
        ///ариведерчи
        ///асеньки
        ///асса
        ///ась
        ///атанда
        ///атанде
        ///атас
        ///ату
        ///ать
        ///ау
        ///ах
        ///ах вон что
        ///ах вот как
        ///ах вот что
        ///ах так
        ///ах ты
        ///ахти
        ///ахти-хти
        ///ба
        ///баиньки
        ///баиньки-баю
        ///бай-бай
        ///банзай
        ///баста
        ///бац
        ///баю
        ///баю-бай
        ///баю-баюшки-б [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Interjections {
            get {
                return ResourceManager.GetString("Interjections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to адажио
        ///аллегретто
        ///аллегри
        ///аллегро
        ///альпари
        ///ара
        ///арпеджио
        ///ассорти
        ///ателье
        ///атташе
        ///барокко
        ///бенгали
        ///бигуди
        ///биде
        ///бикини
        ///бильбоке
        ///бистро
        ///бланманже
        ///болеро
        ///бордо
        ///бра
        ///бренди
        ///боржоми
        ///брокколи
        ///брутто
        ///буги-вуги
        ///бунгало
        ///буржуа
        ///буриме
        ///бюро
        ///варьете
        ///вето
        ///видео
        ///визави
        ///виски
        ///врио
        ///галифе
        ///гало
        ///гестапо
        ///гетто
        ///глясе
        ///гофре
        ///граве
        ///граффити
        ///гризли
        ///гуппи
        ///гуру
        ///декольте
        ///денди
        ///депо
        ///дефиле
        ///дзюдо
        ///динамо
        ///динго
        ///диско
        ///домино
        ///досье
        ///драже
        ///жалюзи
        ///желе
        ///жюри
        ///зеро
        ///индиго
        ///инкогнито
        ///интервь [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Nouns {
            get {
                return ResourceManager.GetString("Nouns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to а,я,ы,и,е,у,ах,ях,ов,ам,ям,ью,ом,ем,ой,ою,ей,ею,ами,ями,ч,г,к,ц,д,инет,енет,рнет,онет,юнет,ось,усь,ась,ись,есь,дь,ж,ш,щ,н,очь,ство,о,ом,ея,от,ех,ах,ох,ух,рх,ях,юх,вх.
        /// </summary>
        internal static string Nouns_ending {
            get {
                return ResourceManager.GetString("Nouns_ending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to один,одного,одному,одним,одном,два,двум,двумя,двух,три,трёх,трём,тремя,сорок,сто,
        ///миллион,миллиард,
        ///много,мало,немало,немного,столько,сколько,несколько.
        /// </summary>
        internal static string Numerical {
            get {
                return ResourceManager.GetString("Numerical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ом,ем,ой,ей,ьей,ых,их,ым,им,ьим,ой,ей,ьей,ыми,ими,ьими,ой,ого,ий,его,ую,ью,ое,ее,ье,ые,ых,ие,их,ьи,ому,ему,ьему,ой,ей,ьей,ым,им,ьим,ого,его,ьего,ой,ей,ьей,ых,их,ьих,ой,ий,ая,ья,ое,ее,ье,ые,ие,ьи.
        /// </summary>
        internal static string Participle_ending {
            get {
                return ResourceManager.GetString("Participle_ending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ущ,ющ.
        /// </summary>
        internal static string Participle_suffix {
            get {
                return ResourceManager.GetString("Participle_suffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to либо,ага,адьё,аж,ажно,аиньки,аминь,ан,аушки,аюшки,б,бишь,будто,буквально,бы,бывает,быловедь,верно,вероятно,вестимо,вишь,во,вон,вот,вот-вот,вроде,вряд,вряд ли,всё,всё-таки,всего,го,да,да уж,давай,давай-ка,даже,дак,де,-де,действительно,дескать,добре,добро,довольно,допустим,дык,едва ли,едва ли не,едва ль,если,ещё,ещё бы,ж,же,замётано,и,или,иль,именно,имхо,ин,инда,индо,ино,исключительно,ить,ишь,-ка,кажется,кайнэ,как,как бы,конечно,куда,ладно,ладушки,ли,лих,лишь,лучше,ль,мол,на,на-тка,навроде,навряд ли,накось,на [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Particles {
            get {
                return ResourceManager.GetString("Particles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to без,ведома,безо,благодаря,близ,вблизи,ввиду,вглубь,вдогон,вдоль,взамен,включая,вкруг,вместо,вне,внизу,внутри,внутрь,вововнутрь,возле,вокруг,вопреки,вослед,впереди,вразрез,вроде,вслед,вследствие,встречу,выключая,для,до,за,замест,заместо,из,изнутри,изо,исключая,исходя из,к,касаемо,касательно,ко,кончая,кроме,кругом,меж,между,мимо,на,на благо,на виду у,на глазах у,на предмет,наверху,навроде,навстречу,над,надо,назад,назади,накануне,наместо,наперекор,наперерез,наперехват,наподобие,напротив,наряду с,насупротив,нас [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Prepositions {
            get {
                return ResourceManager.GetString("Prepositions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to кто,кого,кому,кого,кем,ком,что,чего,чему,что,чем,чём,я,ты,он,она,они,меня,мне,мной,мною,тебя,тебе,тобой,тобою,его,него,ему,нему,им,ним,нём,её,неё,ей,ней,ею,нею,вы,вас,вам,вами,себя,себе,собой,собою,сей,сие,сия,сии,сего,сих,сему,сим,сию,сём,сею,сиею,сими,их,них,им,ним,ими,ними,моё,моя,мои,моего,моей,мои,моему,моим,мою,моих,моим,моей,моею,моими,моём,тот,то,та,те,того,той,тех,тому,тем,ту,тою,теми,том,этот,это,эта,эти,этого,этой,этим,эту,этих,этою,этими,этом,кой,кое,коя,кои,коего,коей,коих,коему,коим,кою,коею,к [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Pronouns {
            get {
                return ResourceManager.GetString("Pronouns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to не.
        /// </summary>
        internal static string Pronouns_console {
            get {
                return ResourceManager.GetString("Pronouns_console", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ой,ое,ая,ие,им,их,ого,ому,ую,ою,ими,ом,ый,ые,ых,ым,ий,его,ему,ем,ё,я,е,
        ///ей,ех,ём,ею,о,а,и,у,ю,ее.
        /// </summary>
        internal static string Pronouns_ending {
            get {
                return ResourceManager.GetString("Pronouns_ending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to как,котор,скольк,ин,нек,весь,вс,всяк,кажд,люб,сам,ваш,наш,свой,сво,твой,тво,стольк,так,эдак,этак,
        ///мног,остальн,проч.
        /// </summary>
        internal static string Pronouns_root {
            get {
                return ResourceManager.GetString("Pronouns_root", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ов,о.
        /// </summary>
        internal static string Pronouns_suffix {
            get {
                return ResourceManager.GetString("Pronouns_suffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to а,а ведь,а именно,а не то,а то,абы,аж,ажно,ай,аки,ако,али,аль,ан,аще,благо,благодаря тому что,благодаря чему,бо,буде,будто,в результате чего,ведь,впрочем,всё,всё-таки,вследствие чего,где,где-то,да,дабы,даже,до тех пор пока не,до тех пор, пока,до того как,докуда,дотоле,егда,едва,еже,ежели,если,ж,же,зане,занеже,зато,зачем,значит,и,или,ибо,из-за того, что,из-за этого,или,иль,именно,имже,иначе,инда,ино,итак,кабы,как,как бы,как бы не,как и,как то,как-то,каков,какой,ковда,ковды,когда,когды,коли,коль,который,куда, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Unions {
            get {
                return ResourceManager.GetString("Unions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ешь,ёшь,ет,ёт,ем,ём,ете,ёте,утют,ишь,ит,им,ите,aтят,
        ///ить,у,ю,еть,ать,ить,оть,уть,ть.
        /// </summary>
        internal static string Verbs_ending {
            get {
                return ResourceManager.GetString("Verbs_ending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ся,сь,ал,али,ело,ало.
        /// </summary>
        internal static string Verbs_postfix {
            get {
                return ResourceManager.GetString("Verbs_postfix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ую,юю,ова,ева,уй,ыва,ива,ываю,иваю,ва,
        ///ёвыва,ене,ени,ини,ствова,ите,и,е,л,а,я,ка,нича,ну,ть,ти.
        /// </summary>
        internal static string Verbs_suffix {
            get {
                return ResourceManager.GetString("Verbs_suffix", resourceCulture);
            }
        }
    }
}
